# Generated by Django 4.2.5 on 2023-11-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queueman',
            name='type',
        ),
    ]
