# Generated by Django 4.2.5 on 2023-11-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueman', '0002_remove_queueman_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queueman',
            old_name='telephone',
            new_name='phone_number',
        ),
    ]
