# Generated by Django 4.2.5 on 2023-11-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueman', '0003_rename_telephone_queueman_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueman',
            name='star',
            field=models.FloatField(default=5),
        ),
    ]
