# Generated by Django 4.2.5 on 2023-11-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueman', '0004_alter_queueman_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueman',
            name='is_have_queue',
            field=models.BooleanField(default=False),
        ),
    ]
