# Generated by Django 4.2.6 on 2023-11-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueman', '0005_queueman_is_have_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueman',
            name='upload',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
