# Generated by Django 4.2.6 on 2023-11-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueman', '0006_queueman_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueman',
            name='upload',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
