# Generated by Django 4.2.6 on 2023-11-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_info_book'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.user_info'),
        ),
    ]
