# Generated by Django 4.2.6 on 2023-11-15 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0002_alter_booking_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
