# Generated by Django 4.2.5 on 2023-11-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_alter_operation_date_alter_operation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='number_Queue',
            field=models.IntegerField(),
        ),
    ]
