# Generated by Django 4.2.6 on 2023-11-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_alter_booking_customer_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operation',
            new_name='Operations',
        ),
    ]
