# Generated by Django 4.2.6 on 2023-11-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_rename_operation_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
