# Generated by Django 4.2.5 on 2023-11-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_alter_operation_number_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='number_Queue',
            field=models.IntegerField(null=True),
        ),
    ]
