# Generated by Django 4.2.6 on 2023-11-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_alter_booking_number_of_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='number_of_customer',
            field=models.IntegerField(null=True),
        ),
    ]
