# Generated by Django 4.2.5 on 2023-11-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_alter_operation_update_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='temp',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
