# Generated by Django 4.2.6 on 2023-11-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_operation_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='cus_phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='que_phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
