# Generated by Django 4.2.6 on 2023-11-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historically',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('restaurant', models.CharField(max_length=30, unique=True)),
                ('cost', models.CharField(max_length=30)),
                ('queeuManName', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField(max_length=30, unique=True)),
                ('phone_number_QueueMan', models.CharField(max_length=30, unique=True)),
                ('phone_number_customer', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('line_id', models.CharField(max_length=30, unique=True)),
                ('location', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
