# Generated by Django 4.2.6 on 2023-11-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_restaurant_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='upload',
            field=models.ImageField(default=None, null=True, upload_to='uploads/'),
        ),
    ]
