# Generated by Django 4.2.5 on 2023-11-24 14:12

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_restaurant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location_address',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(max_length=30),
        ),
    ]
