# Generated by Django 4.2.6 on 2023-11-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_restaurant_location_address_and_more'),
        ('customers', '0009_alter_restaurant_upload'),
    ]

    operations = [
    ]
