# Generated by Django 4.2.6 on 2023-11-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_merge_20231125_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='upload',
            field=models.ImageField(default=None, null=True, upload_to='uploads/'),
        ),
    ]
