# Generated by Django 4.2.6 on 2023-11-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_restaurant_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='upload',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
