# Generated by Django 4.2.6 on 2023-11-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_merge_20231125_0357'),
        ('customers', '0012_alter_restaurant_upload'),
    ]

    operations = [
    ]
