# Generated by Django 4.2.6 on 2023-11-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_merge_20231126_1847'),
        ('customers', '0014_alter_restaurant_location_address'),
    ]

    operations = [
    ]
