# Generated by Django 4.2.6 on 2023-11-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='password',
        ),
    ]
