# Generated by Django 4.2.5 on 2023-11-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_user_info_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='credit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
