# Generated by Django 4.2.5 on 2023-11-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_info_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='type',
        ),
    ]
