# Generated by Django 4.2.6 on 2023-11-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_user_info_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='verify_gmail',
            field=models.BooleanField(default=False),
        ),
    ]
