# Generated by Django 4.2.6 on 2023-11-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_info_verify_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='booking_restaurant',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
