# Generated by Django 4.2.6 on 2023-11-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_user_info_booking_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='booking_restaurant',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
