# Generated by Django 4.2.6 on 2023-11-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_restaurant_upload'),
        ('login', '0009_remove_user_info_booking_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='booking_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.restaurant'),
        ),
    ]
