# Generated by Django 4.2.6 on 2023-11-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_user_info_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='upload',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
