# Generated by Django 4.2.6 on 2023-11-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_user_info_credit_topup_user_info_message_from_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='message_from_admin',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
